apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
        - name: frontend
          # image: kdprasad028/frontend:v1
          image: joindevops/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  # type: LoadBalancer #COMMENT THIS LB we are creating web alb for our control
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
    - name: frontend-port
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: expense
spec:
  serviceRef:
    name: awesome-service # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:537124943253:targetgroup/expense-dev/b736b3c0877982ec #<arn-to-targetGroup>
  targetType: ip